services:
    db:
      image: postgres
      restart: always
      shm_size: 256mb
      environment:
        POSTGRES_USER: nahid
        POSTGRES_PASSWORD: fakepassword
        POSTGRES_DB: database
      ports:
        - 5432:5432
      networks:
        - db_network
    admin:
      image: dpage/pgadmin4
      restart: always
      depends_on:
        - db
      ports:
        - 8080:80
      environment:
        PGADMIN_DEFAULT_EMAIL: admin-nahid@gmail.com
        PGADMIN_DEFAULT_PASSWORD: verystrongpass
      networks:
        - admin_network
        - db_network
networks:
    db_network:
    admin_network:
