services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: nahid
        POSTGRES_PASSWORD: fakepassword
        POSTGRES_DB: database
      networks:
        - db_network
      volumes:
        - db_data:/var/lib/postgres
    admin:
      image: dpage/pgadmin4
      restart: always
      depends_on:
        - db
      ports:
        - 8888:80
      environment:
        PGADMIN_DEFAULT_EMAIL: admin-nahid@gmail.com
        PGADMIN_DEFAULT_PASSWORD: verystrongpass
      networks:
        - db_network

networks:
    db_network:

volumes:
    db_data:
